name: Pull Request

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pullrequest:
    if: ${{ github.actor != 'dependabot[bot]' }}
    uses: Wivik/linux-explained/.github/workflows/release.yml@main
    with:
      prerelease: true
