name: Produce pandoc export

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      prelease:
        default: false
        description: 'Publish release as a prelease'
        type: boolean
  
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Write epub
        uses: docker://pandoc/core:2.9
        with:
          args: "-o linux-explained.epub linux-explained.md"

      - name: Produce release note
        uses: TriPSs/conventional-changelog-action@v3
        id: changelog
        with:
          github-token: ${{ secrets.github_token }}
          version-file: './version_file.json'

      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.changelog.outputs.clean_changelog }}
          tag_name: ${{ steps.changelog.outputs.tag }}
          prerelease: ${{ inputs.prelease }}
          files: |
            linux-explained.epub
          
          
          
          
          
          
          
          
