name: Release epub

on:
  workflow_dispatch:
    inputs:
      prerelease:
        type: boolean
        description: Is it a prerelease ?
        default: false
  workflow_call:
    inputs:
      prerelease:
        type: boolean
        description: Is it a prerelease ?
        default: true


jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      prelease: ${{ inputs.prerelease }}
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch files in workspace
        id: book-files
        run: echo BOOK_FILES=$(ls book/00-*.md book/01-*.md) >> $GITHUB_OUTPUT

      - name: Write epub
        uses: docker://pandoc/core:2.9
        with:
          args: "-o linux-explained.epub --resource-path=.:book ${{ steps.book-files.outputs.BOOK_FILES }} --standalone --toc"

      - name: Produce release note
        uses: TriPSs/conventional-changelog-action@v3
        id: changelog
        with:
          github-token: ${{ secrets.github_token }}
          version-file: './version_file.json'
          pre-release: ${{ env.prerelease }}

      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.changelog.outputs.clean_changelog }}
          tag_name: ${{ steps.changelog.outputs.tag }}
          prerelease: ${{ env.prerelease }}
          files: |
            linux-explained.epub

